package com.snowdango.violet.view.style

import androidx.compose.ui.graphics.Color
import com.airbnb.android.showkase.annotation.ShowkaseColor

// generated by https://m3.material.io/theme-builder#/custom

@ShowkaseColor(group = "Light", name = "Primary")
val md_theme_light_primary = Color(0xFF006874)

@ShowkaseColor(group = "Light", name = "onPrimary")
val md_theme_light_onPrimary = Color(0xFFFFFFFF)

@ShowkaseColor(group = "Light", name = "PrimaryContainer")
val md_theme_light_primaryContainer = Color(0xFF97F0FF)

@ShowkaseColor(group = "Light", name = "onPrimaryContainer")
val md_theme_light_onPrimaryContainer = Color(0xFF001F24)

@ShowkaseColor(group = "Light", name = "Secondary")
val md_theme_light_secondary = Color(0xFF006685)

@ShowkaseColor(group = "Light", name = "onSecondary")
val md_theme_light_onSecondary = Color(0xFFFFFFFF)

@ShowkaseColor(group = "Light", name = "SecondaryContainer")
val md_theme_light_secondaryContainer = Color(0xFFBFE9FF)

@ShowkaseColor(group = "Light", name = "onSecondaryContainer")
val md_theme_light_onSecondaryContainer = Color(0xFF001F2A)

@ShowkaseColor(group = "Light", name = "Tertiary")
val md_theme_light_tertiary = Color(0xFF00658C)

@ShowkaseColor(group = "Light", name = "onTertiary")
val md_theme_light_onTertiary = Color(0xFFFFFFFF)

@ShowkaseColor(group = "Light", name = "TertiaryContainer")
val md_theme_light_tertiaryContainer = Color(0xFFC5E7FF)

@ShowkaseColor(group = "Light", name = "onTertiaryContainer")
val md_theme_light_onTertiaryContainer = Color(0xFF001E2D)

@ShowkaseColor(group = "Light", name = "Error")
val md_theme_light_error = Color(0xFFBA1A1A)

@ShowkaseColor(group = "Light", name = "ErrorContainer")
val md_theme_light_errorContainer = Color(0xFFFFDAD6)

@ShowkaseColor(group = "Light", name = "onError")
val md_theme_light_onError = Color(0xFFFFFFFF)

@ShowkaseColor(group = "Light", name = "onErrorContainer")
val md_theme_light_onErrorContainer = Color(0xFF410002)

@ShowkaseColor(group = "Light", name = "Background")
val md_theme_light_background = Color(0xFFF8FDFF)

@ShowkaseColor(group = "Light", name = "onBackground")
val md_theme_light_onBackground = Color(0xFF001F25)

@ShowkaseColor(group = "Light", name = "Surface")
val md_theme_light_surface = Color(0xFFF8FDFF)

@ShowkaseColor(group = "Light", name = "onSurface")
val md_theme_light_onSurface = Color(0xFF001F25)

@ShowkaseColor(group = "Light", name = "SurfaceVariant")
val md_theme_light_surfaceVariant = Color(0xFFDBE4E6)

@ShowkaseColor(group = "Light", name = "onSurfaceVariant")
val md_theme_light_onSurfaceVariant = Color(0xFF3F484A)

@ShowkaseColor(group = "Light", name = "Outline")
val md_theme_light_outline = Color(0xFF6F797A)

@ShowkaseColor(group = "Light", name = "InverseOnSurface")
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)

@ShowkaseColor(group = "Light", name = "InverseSurface")
val md_theme_light_inverseSurface = Color(0xFF00363F)

@ShowkaseColor(group = "Light", name = "InversePrimary")
val md_theme_light_inversePrimary = Color(0xFF4FD8EB)

@ShowkaseColor(group = "Light", name = "Shadow")
val md_theme_light_shadow = Color(0xFF000000)

@ShowkaseColor(group = "Light", name = "SurfaceTint")
val md_theme_light_surfaceTint = Color(0xFF006874)

@ShowkaseColor(group = "Light", name = "OutlineVariant")
val md_theme_light_outlineVariant = Color(0xFFBFC8CA)

@ShowkaseColor(group = "Light", name = "Scrim")
val md_theme_light_scrim = Color(0xFF000000)

@ShowkaseColor(group = "Dark", name = "Primary")
val md_theme_dark_primary = Color(0xFF4FD8EB)

@ShowkaseColor(group = "Dark", name = "onPrimary")
val md_theme_dark_onPrimary = Color(0xFF00363D)

@ShowkaseColor(group = "Dark", name = "PrimaryContainer")
val md_theme_dark_primaryContainer = Color(0xFF004F58)

@ShowkaseColor(group = "Dark", name = "onPrimaryContainer")
val md_theme_dark_onPrimaryContainer = Color(0xFF97F0FF)

@ShowkaseColor(group = "Dark", name = "Secondary")
val md_theme_dark_secondary = Color(0xFF6CD2FF)

@ShowkaseColor(group = "Dark", name = "onSecondary")
val md_theme_dark_onSecondary = Color(0xFF003547)

@ShowkaseColor(group = "Dark", name = "SecondaryContainer")
val md_theme_dark_secondaryContainer = Color(0xFF004D65)

@ShowkaseColor(group = "Dark", name = "onSecondaryContainer")
val md_theme_dark_onSecondaryContainer = Color(0xFFBFE9FF)

@ShowkaseColor(group = "Dark", name = "Tertiary")
val md_theme_dark_tertiary = Color(0xFF7FD0FF)

@ShowkaseColor(group = "Dark", name = "onTertiary")
val md_theme_dark_onTertiary = Color(0xFF00344A)

@ShowkaseColor(group = "Dark", name = "TertiaryContainer")
val md_theme_dark_tertiaryContainer = Color(0xFF004C6A)

@ShowkaseColor(group = "Dark", name = "onTertiaryContainer")
val md_theme_dark_onTertiaryContainer = Color(0xFFC5E7FF)

@ShowkaseColor(group = "Dark", name = "Error")
val md_theme_dark_error = Color(0xFFFFB4AB)

@ShowkaseColor(group = "Dark", name = "ErrorContainer")
val md_theme_dark_errorContainer = Color(0xFF93000A)

@ShowkaseColor(group = "Dark", name = "onError")
val md_theme_dark_onError = Color(0xFF690005)

@ShowkaseColor(group = "Dark", name = "onErrorContainer")
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)

@ShowkaseColor(group = "Dark", name = "Background")
val md_theme_dark_background = Color(0xFF001F25)

@ShowkaseColor(group = "Dark", name = "onBackground")
val md_theme_dark_onBackground = Color(0xFFA6EEFF)

@ShowkaseColor(group = "Dark", name = "Surface")
val md_theme_dark_surface = Color(0xFF001F25)

@ShowkaseColor(group = "Dark", name = "onSurface")
val md_theme_dark_onSurface = Color(0xFFA6EEFF)

@ShowkaseColor(group = "Dark", name = "SurfaceVariant")
val md_theme_dark_surfaceVariant = Color(0xFF3F484A)

@ShowkaseColor(group = "Dark", name = "onSurfaceVariant")
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CA)

@ShowkaseColor(group = "Dark", name = "Outline")
val md_theme_dark_outline = Color(0xFF899294)

@ShowkaseColor(group = "Dark", name = "InverseOnSurface")
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)

@ShowkaseColor(group = "Dark", name = "InverseSurface")
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)

@ShowkaseColor(group = "Dark", name = "InversePrimary")
val md_theme_dark_inversePrimary = Color(0xFF006874)

@ShowkaseColor(group = "Dark", name = "Shadow")
val md_theme_dark_shadow = Color(0xFF000000)

@ShowkaseColor(group = "Dark", name = "SurfaceTint")
val md_theme_dark_surfaceTint = Color(0xFF4FD8EB)

@ShowkaseColor(group = "Dark", name = "OutlineVariant")
val md_theme_dark_outlineVariant = Color(0xFF3F484A)

@ShowkaseColor(group = "Dark", name = "Scrim")
val md_theme_dark_scrim = Color(0xFF000000)
