name: Android CI

on:
  push:
    branches: [ "master", "develop", "feature/*" ]

jobs:
  container-tests:
    runs-on: ubuntu-latest
    container:
      image: us-docker.pkg.dev/android-emulator-268719/images/28-playstore-x64:30.1.2
      ports:
        - "5555:5555"
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          ndk: 21.0.6113669
          cmake: 3.10.2.4988404
          script: ./gradlew connectedAndroidTest